### ISSUE TITLE
No Config File / No Configurability - Want to re-add

### ISSUE THREAD

**Issue by asheden** [RicoValdezio/RoR2-GeneticsArtifact#27]

**Comment by Argel-Tal** [comment]
In the R2Modman client, check config

**Comment by RicoValdezio** [comment]
Currently there isn't a config file for this, as that was removed as part of the 4.X rewrite. I'm currently discussing the new config needs in the modding discord here: https://discord.com/channels/562704639141740588/967098605997551687
Also, going to rename this topic to match the want.
