### ISSUE TITLE
Would GeneticArtifact work with ArtifactsRandomizer?

### ISSUE THREAD

**Issue by Agitatio** [RicoValdezio/RoR2-GeneticsArtifact#33]
Or does it have to be on for the whole run from the start to properly work? Couldn't contact you on the modding Discord so I'm reaching out here.

**Comment by RicoValdezio** [comment]
It can be enabled/disabled at any point during the run. Actually had to add a special "Emergency Start" system to make sure that it would work for the Bulwark/Challenge. My understanding is that ArtifactsRandomizer would trigger that the same way and - besides maybe a frame or two of startup lag - start working as if you started the run with it.
